name: booking_hotels
description: "tutorial sur la création d'une app sur la réservation d'hotels."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hotel_1.png
    - assets/images/hotel_2.png
    - assets/images/hotel_3.png
    - assets/images/hotel_4.png